"""empty message

Revision ID: 015f727ddaed
Revises: 7fe4840d48b7
Create Date: 2018-07-01 23:43:45.317297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '015f727ddaed'
down_revision = '7fe4840d48b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('price', postgresql.DOUBLE_PRECISION(), server_default=sa.text('0'), nullable=False))
    op.drop_column('purchases', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('status', sa.SMALLINT(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('purchases', 'price')
    # ### end Alembic commands ###
