"""empty message

Revision ID: 06f1f9d53db3
Revises: 
Create Date: 2018-04-12 13:44:21.092799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06f1f9d53db3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('langitude', postgresql.DOUBLE_PRECISION(), nullable=False),
    sa.Column('latitude', postgresql.DOUBLE_PRECISION(), nullable=False),
    sa.Column('addr1', sa.TEXT(), nullable=False),
    sa.Column('addr2', sa.TEXT(), nullable=True),
    sa.Column('addr3', sa.TEXT(), nullable=True),
    sa.Column('city', sa.TEXT(), nullable=False),
    sa.Column('state', sa.TEXT(), nullable=False),
    sa.Column('country', sa.TEXT(), nullable=False),
    sa.Column('postcode', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('family_name', sa.TEXT(), nullable=False),
    sa.Column('given_name', sa.TEXT(), nullable=False),
    sa.Column('gender', sa.TEXT(), nullable=True),
    sa.Column('dob', sa.DATE(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('source_type', sa.TEXT(), nullable=True),
    sa.Column('avartar', postgresql.BYTEA(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wechatUsers',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('openid', sa.TEXT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('location_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], [u'locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('babies',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('family_name', sa.TEXT(), nullable=False),
    sa.Column('given_name', sa.TEXT(), nullable=False),
    sa.Column('gender', sa.TEXT(), nullable=True),
    sa.Column('dob', sa.DATE(), nullable=False),
    sa.Column('parent_id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('babies')
    op.drop_table('activities')
    op.drop_table('wechatUsers')
    op.drop_table('users')
    op.drop_table('locations')
    # ### end Alembic commands ###
