"""empty message

Revision ID: 0a08aec805d0
Revises: a3afd45bc9a7
Create Date: 2018-05-07 08:58:54.147549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a08aec805d0'
down_revision = 'a3afd45bc9a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_password_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_password_key', 'users', ['password'])
    # ### end Alembic commands ###
