"""empty message

Revision ID: 0cb12390f384
Revises: 85e94afb447d
Create Date: 2018-05-11 22:20:25.581017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0cb12390f384'
down_revision = '85e94afb447d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_images',
    sa.Column('activity_image_id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('activity_id', postgresql.UUID(), nullable=False),
    sa.Column('image_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.image_id'], ),
    sa.PrimaryKeyConstraint('activity_image_id')
    )
    op.drop_column('images', 'creator_id')
    op.drop_column('images', 'created_at')
    op.drop_column('images', 'linked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('linked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('images', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('images', sa.Column('creator_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_table('activity_images')
    # ### end Alembic commands ###
