"""empty message

Revision ID: 0ec946b4826a
Revises: 3b3e78d86397
Create Date: 2018-05-22 00:13:50.017810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec946b4826a'
down_revision = '3b3e78d86397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('status', sa.SMALLINT(), server_default = sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'status')
    # ### end Alembic commands ###
