"""empty message

Revision ID: 204fe9e844e4
Revises: e244163882c1
Create Date: 2018-06-01 23:06:18.517830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204fe9e844e4'
down_revision = 'e244163882c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('category', sa.INTEGER(), nullable=True))
    op.alter_column('activities', 'status',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'status',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.drop_column('activities', 'category')
    # ### end Alembic commands ###
