"""empty message

Revision ID: 289083409a28
Revises: 5e10ad1f4362
Create Date: 2018-04-12 22:18:32.944257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289083409a28'
down_revision = '5e10ad1f4362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wechat_users', sa.Column('avartar_url', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wechat_users', 'avartar_url')
    # ### end Alembic commands ###
