"""empty message

Revision ID: 33e674c9e0c7
Revises: 0a8e9e04fc61
Create Date: 2018-04-28 17:45:10.865648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33e674c9e0c7'
down_revision = '0a8e9e04fc61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.Column('access_token', sa.TEXT(), nullable=True),
    sa.Column('access_token_expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('refresh_token', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    # ### end Alembic commands ###
