"""empty message

Revision ID: 3933ab4b0b5e
Revises: 7f5ddb45e9a4
Create Date: 2018-06-20 13:28:06.429860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3933ab4b0b5e'
down_revision = '7f5ddb45e9a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
    sa.Column('purchase_id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('activity_id', postgresql.UUID(), nullable=False),
    sa.Column('provider_id', postgresql.UUID(), nullable=False),
    sa.Column('booked_by', postgresql.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ),
    sa.ForeignKeyConstraint(['booked_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], ),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    op.add_column('vacancies', sa.Column('purchase_id', postgresql.UUID(), nullable=True))
    op.drop_constraint('vacancies_booked_by_fkey', 'vacancies', type_='foreignkey')
    op.create_foreign_key(None, 'vacancies', 'purchases', ['purchase_id'], ['purchase_id'])
    op.drop_column('vacancies', 'booked_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('booked_by', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.create_foreign_key('vacancies_booked_by_fkey', 'vacancies', 'users', ['booked_by'], ['user_id'])
    op.drop_column('vacancies', 'purchase_id')
    op.drop_table('purchases')
    # ### end Alembic commands ###
