"""empty message

Revision ID: 3b3e78d86397
Revises: 9ca290a04e0f
Create Date: 2018-05-21 23:35:44.808239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b3e78d86397'
down_revision = '9ca290a04e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('gender', sa.SMALLINT(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'gender')
    # ### end Alembic commands ###
