"""empty message

Revision ID: 3db3b28ebbf4
Revises: dc0f76ba52fe
Create Date: 2018-06-05 01:00:15.432138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3db3b28ebbf4'
down_revision = 'dc0f76ba52fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_reviews',
    sa.Column('review_id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('activity_id', postgresql.UUID(), nullable=False),
    sa.Column('reviewer_id', postgresql.UUID(), nullable=False),
    sa.Column('stars', sa.SMALLINT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('activity_responses',
    sa.Column('response_id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('review_id', postgresql.UUID(), nullable=False),
    sa.Column('activity_id', postgresql.UUID(), nullable=False),
    sa.Column('provider_id', postgresql.UUID(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['activity_reviews.review_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_responses')
    op.drop_table('activity_reviews')
    # ### end Alembic commands ###
