"""empty message

Revision ID: 413d3f6513c9
Revises: 289083409a28
Create Date: 2018-04-15 22:53:45.595101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '413d3f6513c9'
down_revision = '289083409a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('babies', sa.Column('full_name', sa.TEXT(), nullable=True))
    op.alter_column('babies', 'family_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('babies', 'given_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('users', sa.Column('full_name', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('nick_name', sa.TEXT(), nullable=True))
    op.alter_column('users', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'family_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'given_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('users', 'source_type')
    op.drop_column('users', 'avartar')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('avartar', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('source_type', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('users', 'given_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'family_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('users', 'nick_name')
    op.drop_column('users', 'full_name')
    op.alter_column('babies', 'given_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('babies', 'family_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('babies', 'full_name')
    # ### end Alembic commands ###
