"""empty message

Revision ID: 591f5dc3ffbd
Revises: edf5a77809c0
Create Date: 2018-05-16 22:54:06.908120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591f5dc3ffbd'
down_revision = 'edf5a77809c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'salt',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'salt',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
