"""empty message

Revision ID: 5e10ad1f4362
Revises: 06f1f9d53db3
Create Date: 2018-04-12 13:49:15.059485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e10ad1f4362'
down_revision = '06f1f9d53db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wechat_users',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('openid', sa.TEXT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('wechatUsers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wechatUsers',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('openid', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'wechatUsers_pkey')
    )
    op.drop_table('wechat_users')
    # ### end Alembic commands ###
