"""empty message

Revision ID: 63768df5b0b3
Revises: 7190cf77de52
Create Date: 2018-05-06 13:47:05.313450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63768df5b0b3'
down_revision = '7190cf77de52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('activity_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('activities_location_id_fkey', 'activities', type_='foreignkey')
    op.create_foreign_key(None, 'activities', 'locations', ['location_id'], ['location_id'])
    op.drop_column('activities', 'id')
    op.add_column('babies', sa.Column('baby_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('babies_parent_id_fkey', 'babies', type_='foreignkey')
    op.create_foreign_key(None, 'babies', 'users', ['parent_id'], ['user_id'])
    op.drop_column('babies', 'id')
    op.add_column('locations', sa.Column('location_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('locations', 'id')
    op.add_column('sessions', sa.Column('session_id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False))
    op.drop_constraint('sessions_user_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['user_id'])
    op.drop_column('sessions', 'id')
    op.add_column('users', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('users', 'id')
    op.add_column('wechat_users', sa.Column('open_id', sa.TEXT(), nullable=False))
    op.add_column('wechat_users', sa.Column('wechat_user_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('wechat_users', 'id')
    op.drop_column('wechat_users', 'openid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wechat_users', sa.Column('openid', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('wechat_users', sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('wechat_users', 'wechat_user_id')
    op.drop_column('wechat_users', 'open_id')
    op.add_column('users', sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('users', 'user_id')
    op.add_column('sessions', sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_user_id_fkey', 'sessions', 'users', ['user_id'], ['id'])
    op.drop_column('sessions', 'session_id')
    op.add_column('locations', sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('locations', 'location_id')
    op.add_column('babies', sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'babies', type_='foreignkey')
    op.create_foreign_key('babies_parent_id_fkey', 'babies', 'users', ['parent_id'], ['id'])
    op.drop_column('babies', 'baby_id')
    op.add_column('activities', sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.create_foreign_key('activities_location_id_fkey', 'activities', 'locations', ['location_id'], ['id'])
    op.drop_column('activities', 'activity_id')
    # ### end Alembic commands ###
