"""empty message

Revision ID: 6391cc06cd35
Revises: 0a08aec805d0
Create Date: 2018-05-07 15:14:34.033027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6391cc06cd35'
down_revision = '0a08aec805d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'account_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'account_name',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
