"""empty message

Revision ID: 65593e214f22
Revises: b74564cfb73f
Create Date: 2018-05-06 22:17:17.319892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65593e214f22'
down_revision = 'b74564cfb73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('babies', sa.Column('info', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('babies', 'info')
    # ### end Alembic commands ###
