"""empty message

Revision ID: 6a1d150a2788
Revises: 204fe9e844e4
Create Date: 2018-06-01 23:40:55.503931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a1d150a2788'
down_revision = '204fe9e844e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('days_of_week', sa.SMALLINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'days_of_week')
    # ### end Alembic commands ###
