"""empty message

Revision ID: 7190cf77de52
Revises: c1ea4d4dffab
Create Date: 2018-05-06 12:05:25.795253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7190cf77de52'
down_revision = 'c1ea4d4dffab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('filename', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'filename')
    # ### end Alembic commands ###
