"""empty message

Revision ID: 7f5ddb45e9a4
Revises: 0e5a1b60304a
Create Date: 2018-06-15 00:06:12.979884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f5ddb45e9a4'
down_revision = '0e5a1b60304a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wechat_users', sa.Column('wechat_nick_name', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wechat_users', 'wechat_nick_name')
    # ### end Alembic commands ###
