"""empty message

Revision ID: 7fe4840d48b7
Revises: 91fbea894f78
Create Date: 2018-06-27 22:41:04.701453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fe4840d48b7'
down_revision = '91fbea894f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('baby_id', postgresql.UUID(), nullable=False))
    op.create_foreign_key(None, 'purchases', 'babies', ['baby_id'], ['baby_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'baby_id')
    # ### end Alembic commands ###
