"""empty message

Revision ID: 85e94afb447d
Revises: 81fb988661ca
Create Date: 2018-05-10 21:45:57.723374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e94afb447d'
down_revision = '81fb988661ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('images_creator_id_fkey', 'images', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('images_creator_id_fkey', 'images', 'users', ['creator_id'], ['user_id'])
    # ### end Alembic commands ###
