"""empty message

Revision ID: 91fbea894f78
Revises: b0c3df9425e7
Create Date: 2018-06-25 22:54:53.359151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91fbea894f78'
down_revision = 'b0c3df9425e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('end_date', sa.DATE(), nullable=False))
    op.add_column('purchases', sa.Column('start_date', sa.DATE(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'start_date')
    op.drop_column('purchases', 'end_date')
    # ### end Alembic commands ###
