"""empty message

Revision ID: 9ca290a04e0f
Revises: 5cc935d9eeb5
Create Date: 2018-05-21 17:32:47.479073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca290a04e0f'
down_revision = '5cc935d9eeb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('map_service', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'map_service')
    # ### end Alembic commands ###
