"""empty message

Revision ID: b0c3df9425e7
Revises: 3933ab4b0b5e
Create Date: 2018-06-24 09:10:55.576912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c3df9425e7'
down_revision = '3933ab4b0b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('status', sa.SMALLINT(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'status')
    # ### end Alembic commands ###
