"""empty message

Revision ID: b6ce8e5c15bf
Revises: 015f727ddaed
Create Date: 2018-07-01 23:47:08.372625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ce8e5c15bf'
down_revision = '015f727ddaed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('status', sa.SMALLINT(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'status')
    # ### end Alembic commands ###
