"""empty message

Revision ID: b76f17caa4e7
Revises: 3db3b28ebbf4
Create Date: 2018-06-06 21:42:55.181020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b76f17caa4e7'
down_revision = '3db3b28ebbf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('favorate_id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('activity_id', postgresql.UUID(), nullable=False),
    sa.Column('provider_id', postgresql.UUID(), nullable=False),
    sa.Column('consumer_id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ),
    sa.ForeignKeyConstraint(['consumer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('favorate_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
