"""empty message

Revision ID: b76f17caa4e7
Revises: 3db3b28ebbf4
Create Date: 2018-06-06 21:42:55.181020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b76f17caa4e7'
down_revision = '3db3b28ebbf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
