"""empty message

Revision ID: c1cb35bf8e53
Revises: 591f5dc3ffbd
Create Date: 2018-05-20 10:09:18.400104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1cb35bf8e53'
down_revision = '591f5dc3ffbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activity_images_image_id_fkey', 'activity_images', type_='foreignkey')
    op.create_foreign_key(None, 'activity_images', 'images', ['activity_image_id'], ['image_id'])
    op.drop_column('activity_images', 'image_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_images', sa.Column('image_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'activity_images', type_='foreignkey')
    op.create_foreign_key('activity_images_image_id_fkey', 'activity_images', 'images', ['image_id'], ['image_id'])
    # ### end Alembic commands ###
