"""empty message

Revision ID: cd42941ecab2
Revises: f85406c653af
Create Date: 2018-05-27 12:57:00.145857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd42941ecab2'
down_revision = 'f85406c653af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'city',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('venues', 'country',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('venues', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('venues', 'state',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'state',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('venues', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('venues', 'country',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('venues', 'city',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
