"""empty message

Revision ID: e244163882c1
Revises: cd42941ecab2
Create Date: 2018-05-27 17:18:20.965340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e244163882c1'
down_revision = 'cd42941ecab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'status',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'status',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###
