"""empty message

Revision ID: e3d0dfb4cc2c
Revises: 6391cc06cd35
Create Date: 2018-05-07 22:56:47.318374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3d0dfb4cc2c'
down_revision = '6391cc06cd35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('babies', sa.Column('creator_id', postgresql.UUID(), nullable=False))
    op.add_column('babies', sa.Column('nick_name', sa.TEXT(), nullable=True))
    op.drop_constraint('babies_parent_id_fkey', 'babies', type_='foreignkey')
    op.create_foreign_key(None, 'babies', 'users', ['creator_id'], ['user_id'])
    op.drop_column('babies', 'parent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('babies', sa.Column('parent_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'babies', type_='foreignkey')
    op.create_foreign_key('babies_parent_id_fkey', 'babies', 'users', ['parent_id'], ['user_id'])
    op.drop_column('babies', 'nick_name')
    op.drop_column('babies', 'creator_id')
    # ### end Alembic commands ###
