"""empty message

Revision ID: edf5a77809c0
Revises: 04c651758f8b
Create Date: 2018-05-13 22:17:25.891566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'edf5a77809c0'
down_revision = '04c651758f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('currency', sa.TEXT(), nullable=True))
    op.add_column('activities', sa.Column('price', postgresql.DOUBLE_PRECISION(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'price')
    op.drop_column('activities', 'currency')
    # ### end Alembic commands ###
