"""empty message

Revision ID: efd80a36c8b2
Revises: 0ec946b4826a
Create Date: 2018-05-22 00:16:14.290905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd80a36c8b2'
down_revision = '0ec946b4826a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'status',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'status',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###
